### ISSUE TITLE
Package 'yadda' not found

### ISSUE THREAD

**Issue by mschinis** [curit/ember-cli-yadda#10]
Hello,

When I install this package using `ember install ember-cli-yadda`, the `afterInstall` function in `blueprints/main-index.js` fails to find the yadda package to import it.

I forked the project to find a fix, but will definitely be appreciated if you find the issue before me :D

How to reproduce:
1. I'm guessing the yadda package is in your `bower_components` folder, so you would probably have to delete it to reproduce.
2. run `ember install ember-cli-yadda`

**Comment by albertjan** [comment]
Looking into it.

**Comment by albertjan** [comment]
I'm assuming you're using ember-cli 1.13

**Comment by albertjan** [comment]
I just did this on my machine without issues :smile: 

```shell
$ ember new yadda-test-2
$ bower cache clean
$ ember install ember-cli-yadda
Installed packages for tooling via npm.
installing ember-cli-yadda
  create tests\acceptance\steps\steps.js
Installing browser packages via Bower...
  not-cached git://github.com/acuminous/yadda.git#~0.15.4
  resolved git://github.com/acuminous/yadda.git#0.15.4
Installed browser packages via Bower.
Installed addon package.
```

**Comment by albertjan** [comment]
What happens when you type:

```sh
$ bower install acuminous/yadda#0.15.4
bower yadda#0.15.4              cached git://github.com/acuminous/yadda.git#0.15.4
bower yadda#0.15.4            validate 0.15.4 against git://github.com/acuminous/yadda.git#0.15.4
```

**Comment by mschinis** [comment]
Hello @albertjan, thanks for the quick reply. I eventually ended up finding the issue earlier today. 
I was using `ember-cli v1.13.1`, and when I upgraded to `v1.13.8` everything worked perfectly!

Weird, but it seems to be connected to [this](https://github.com/ember-cli/ember-cli/pull/4643) ember-cli pull request which was released with 1.13.8.
```#4643 Support a (now deprecated) single-argument use of addBowerPackageToProject @mike-north```

**Comment by albertjan** [comment]
We use a call to `addBowerPackagesToProject` that might internally use the `addBowerPackageToProject` with the single argument. I could change that. But I wasn't planning on supporting older versions of ember-cli, just because the width and breadth of the system of rabit holes is staggering :smile:

Don't hesitate to ask any other questions. (I'm also on the emberjs slack chat: https://ember-community-slackin.herokuapp.com/)

**Comment by mschinis** [comment]
Yeah `addBowerPackagesToProject` internally calls `addBowerPackageToProject`.

Thanks for the ember-community slack channel! I didn't know it even existed. Just joined!
Feel free to close the issue. I will also be contributing in the near future as soon as I become more familiarised with the addon.

**Comment by albertjan** [comment]
Cool :smile:

**Comment by montoias** [comment]
worked for me also, thanks @mschinis
