### ISSUE TITLE
moduleForComponent implementation

### ISSUE THREAD

**Issue by mschinis** [curit/ember-cli-yadda#11]
Hi,

Trying to test components, missing the ember-cli `moduleForComponent` implementation though. Is there a way to test components with ember-cli-yadda or do I have to extend the plugin to add the module?

Cheers,
Michael

**Comment by albertjan** [comment]
Weird I would have bet this was in there somewhere. It should be. :smile:. I have to think a bit about it though. Maybe we have to make it an option in the feature file with a decoration something like:
`@moduleForComponent pretty-color`

**Comment by mschinis** [comment]
PR #14 adds support for component unit tests :)
