### ISSUE TITLE
tests/helpers/yadda.js not created upon install

### ISSUE THREAD

**Issue by jbryson3** [curit/ember-cli-yadda#12]
Using ember-cli 1.13.8
ember init
ember install ember-cli-yadda

The docs say that tests/helpers/yadda.js should be installed, but I do not see it there. Am I missing something or reading the docs wrong?

**Comment by albertjan** [comment]
@jbryson3 yadda will be installed as a dependency, it won't be added to your code. Where did you read this in the docs? I'll try and clarify.

**Comment by jbryson3** [comment]
> It also adds the following files:

> /tests/helpers/yadda.js

**Comment by albertjan** [comment]
Ah yes I found it, and I've removed it. When we first started we needed a test helper to be injected into the test runtime. It's not longer necessary.

**Comment by albertjan** [comment]
Did you have any issues with the addon?

**Comment by jbryson3** [comment]
No, I didn't realize that importing yadda wouldn't result in an undefined if I didn't see it in my source folders. Thanks for your help!
