### ISSUE TITLE
Cannot read annotations

### ISSUE THREAD

**Issue by edslocombe** [curit/ember-cli-yadda#17]
I think I'm right in saying that I cannot access Yadda annotations, or rather, cannot control which scenarios might be run, using the default test feature template the `index.js` generates. 

I would like to have more configuration options; e.g.
- Skip scenarios with a `@Skip` annotation
- The annotation `@EndToEnd` perhaps suggests that the scenario is only run when not using Mirage

Would we be able to make the test feature output more configurable in some way? 

I may well raise a PR to do this myself if this sounds sensible.

**Comment by remkoboschker** [comment]
@edslocombe Would you like to be able to skip feature entirely or just scenarios?

We can easily filter the scenarios array on scenario.annotation.skip. 

I'm not sure how we would filter on features. Once the file is parsed and the feature has a skip annotation we could return a test file with no tests in it. But it is probably nicer to somehow delete it from the broccoli tree.

**Comment by edslocombe** [comment]
I don't think I'd be too fussed about skipping features but it would be nice. I guess a first-pass solution could be ember features if all scenarios happened to be skipped.

I think whatever the solution, it'd be great if it were configurable and that perhaps arguments from the command line could determine what scenarios were run.

e.g `ember test --tags @smoke`

Much like Cucumber's [tags](https://github.com/cucumber/cucumber/wiki/Tags).

**Comment by remkoboschker** [comment]
Do you know how to pass parameters into the test runner? I'll have look.

**Comment by remkoboschker** [comment]
Yes, ember-cli has a an option to filter on name string and an option to run a specific module. I have not looked at the exact implementation. So if we get the annotations from the features and scenarios how do we make them available in the `-test.js` file that the addon outputs so that we can use them from the testem runner?

**Comment by remkoboschker** [comment]
@edslocombe @albertjan is this still an active issue?

**Comment by edslocombe** [comment]
I haven't got round to doing anything about it but would still love a feature like this. Feel free to close though and I may still take a look at some point.

**Comment by albertjan** [comment]
I don't see any harm in keeping it open, it might trigger somebody to pick it up 👍

**Comment by moogus** [comment]
having this issue myself....trying to access the annotations programatically, feels like I should be able to do something like.

`
import annotations from 'ember-yadda'

if (annotations['myAnnotation']) {
    // Do stuff
}

`

Can't even comment out the whole files as that shows as an empty feature file which fails too.


as per the yadda docs but

**Comment by albertjan** [comment]
@edslocombe Does #38 do it for you? 😉

**Comment by edslocombe** [comment]
Great stuff :)
