### ISSUE TITLE
More than one assert in a single given/when/then

### ISSUE THREAD

**Issue by jackmatt2** [curit/ember-cli-yadda#18]
At the moment only a single `assert` is allowed per function - is this configurable?

**Comment by remkoboschker** [comment]
I'm not sure I understand what you mean.

**Comment by albertjan** [comment]
Morning @remkoboschker :smile: currently only one assertion is expected per line, for the async stuff. It currently isn't configurable.

**Comment by jackmatt2** [comment]
Can this be added as a feature?

**Comment by albertjan** [comment]
We'd need to have a way to tell qunit/mocha how many assertions to expect. It might be possible to do that with an annotation. I'd say have at it :smile:

**Comment by remkoboschker** [comment]
I see, we now just input the number of steps, got it. Should you do more than one assertion per step?

**Comment by albertjan** [comment]
That is a good question. @mschinis you've probably run into this as well would you say this would be a useful addition?

**Comment by mschinis** [comment]
Sorry for the late reply!

I definitely see the reason why this might be handy, but I don't think that the addition of more than assertion per step is correct in the BDD world.

@jackmatt2 I don't know exactly what your gherkin test looks like exactly, but in BDD, each step in a test is considered as one key user interaction/check. I would highly recommend that you split each assertion in it's own separate step.

For example, if you have something like the following:
```gherkin
Given I am on page "/"
Then there should be 10 products and 2 shops
```

This might be a better alternative:
```gherkin
Given I am on page "/"
Then there should be 10 products
And there should be 2 shops
```

Sharing your gherkin test will definitely help answer your question!

**Comment by jackmatt2** [comment]
@mschinis I am pretty new to Gherkin tests.  I will use your advise and try to make sure I only need a single test per line.  Thanks.

**Comment by mschinis** [comment]
Feel free to reach me on the ember community slack group if you need any help :)
