### ISSUE TITLE
Document table usage in README.md

### ISSUE THREAD

**Issue by jackmatt2** [curit/ember-cli-yadda#19]
Document table usage.  In the [video](https://vimeo.com/146828818) there is a demonstration of using a table in tests but there is no documentation in the README.md.

**Comment by remkoboschker** [comment]
You can find more information on these matter overhere: https://www.gitbook.com/book/acuminous/yadda-user-guide/details. Ember-cli-yadda is just a thin wrapper around yadda.

**Comment by jackmatt2** [comment]
Fair enough.  Adding the link to the README somewhere would be great.
