### ISSUE TITLE
Adding yadda to bower.json

### ISSUE THREAD

**Issue by sfbwalder** [curit/ember-cli-yadda#22]
Currently ember-cli-yadda adds the following to the ember project's bower.json:

```
  "yadda": "acuminous/yadda#"
```

We work behind a corporate proxy, and when the bower install attempts to go to github it gets blocked.  We would like to pull yadda from the bower registry rather than github.  Could this be changed to have the following put in bower.json:

```
  "yadda": ">=0"
```

or something similar to pull the latest version from bower instead?

The yadda folks kindly fixed up their bower.json, and it appears this will work [from bower](http://bower.io/search/?q=yadda) now (acuminous/yadda#214).

**Comment by remkoboschker** [comment]
Sure, if you test it and make a pull request. I don't see why we shouldn't merge it. I does mean that the people over at yadda need to publish it consistently to the bower registry.

@albertjan any comments?

**Comment by albertjan** [comment]
Yeah when we need to use master again it's switched back easily enough. I'd merge it 😄
