### ISSUE TITLE
Upgrading our app to 2.9 failing yadda tests

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [curit/ember-cli-yadda#32]
- Recently, I upgraded my app from 2.7 to 2.9 as Qunit is upgraded in this version, my existing yadda BDD tests are also failing. Could you please fix?

<img width="939" alt="screen shot 2016-11-14 at 17 43 35" src="https://cloud.githubusercontent.com/assets/8244992/20275918/2ecc851e-aa92-11e6-974c-f4f3ca70d1fb.png">

**Comment by albertjan** [comment]
@vinodhrajamuralidharan PR has already been merged if you install it from the gitrepo you'll have the latest and greatest that doesn't rely on expect anymore.

**Comment by albertjan** [comment]
you can do that with `npm install curit/ember-cli-yadda`

**Comment by vinodhrajamuralidharan** [comment]
I will try now and update you. Thanks.

**Comment by albertjan** [comment]
addressed in 0.1.0
