### ISSUE TITLE
Better traceability for failing tests

### ISSUE THREAD

**Issue by simonihmig** [curit/ember-cli-yadda#33]
@albertjan as were in a flow right now... ;)

This is basically just an idea, and I am curious on what your opinion is about the following proposal. The problem I have been facing often times with ember-cli-yadda ist that when tests are failing you have no idea where the problem really comes from, because of all the asynchrony and the "broken" stack traces. Not even on which step the error occured.

To make this easier for us, we have been using our fork to actually include the addon, and changed the test setup (Mocha-based) a bit:
* each step is defined as a separate test (`it()` in mocha)
* a scenario wraps all steps in a `describe`
* a feature wraps all scenario in another `describe`
* when a step test is failing, all following steps tests are marked as pending (to prevent them from being run, as they are now defined as kind of independent tests)

Here is an example mocha output of a failing test with that setup:

![bildschirmfoto 2016-11-15 um 19 43 58](https://cloud.githubusercontent.com/assets/1325249/20322131/2cc62068-ab78-11e6-8cd2-7941385f9da8.png)

You can see the code for this here: https://github.com/simonihmig/ember-cli-yadda/tree/mocha-separate-steps

Although this may seem strange at first look, this has served us quite well to easily identify where tests are failing. And it increased the test count considerably, which made us feel more comfortable! (just kidding :))

I wonder if that setup would make sense to be merged back? As a default or maybe as an option? Could put a PR together, as it is already there for Mocha, Qunit though is still missing...

**Comment by albertjan** [comment]
From a layout perspective it looks good to me and I definitely understand the reasoning behind it. People currently using ember-cli-yadda won't be effected they'll only have a better looking results page. 

> when a step test is failing, all following steps tests are marked as pending (to prevent them from being run, as they are now defined as kind of independent tests)

I assume it will run other scenario's and features, it just won't run the other steps in the failing scenario?

Open the PR it's definitely worth looking at 😄

**Comment by simonihmig** [comment]
> I assume it will run other scenario's and features, it just won't run the other steps in the failing scenario?

Sure!

OK, will try to put something together. Might take some days though...

**Comment by albertjan** [comment]
I looked through your code, your sharing the context between steps, is that on purpose?

**Comment by simonihmig** [comment]
I am not sure I understand your point. Isn't that what the context is supposed to do?

**Comment by albertjan** [comment]
:trollface: ah yes you are right, I completely misread that.

**Comment by albertjan** [comment]
Hey @simonihmig any progress on this one? 😄

**Comment by simonihmig** [comment]
Sorry, did not have the time yet unfortunately. But I have not forgotten about this! ;)

**Comment by simonihmig** [comment]
Closed by #37
