### ISSUE TITLE
ember-browserify not being installed in blueprint

### ISSUE THREAD

**Issue by sfbwalder** [curit/ember-cli-yadda#40]
afterInstall() [at this line of code](https://github.com/curit/ember-cli-yadda/blob/master/blueprints/main-index.js#L7) needs to return the promise:

`  return this.addAddonToProject('ember-browserify');`

to have the install wait on ember-browserify to install.

The work around is to manually run `ember install ember-browserify`.

Sorry I didn't catch this earlier when we were looking at the PR.

**Comment by albertjan** [comment]
Thats ok. I'll do it quickly.
