### ISSUE TITLE
Not reporting acceptance test failures

### ISSUE THREAD

**Issue by adamjmcgrath** [curit/ember-cli-yadda#44]
Am seeing that acceptance test failures are ignored with a fresh install (ember 2.12.0) of `ember-cli-mocha` and `ember-cli-yadda` (`separateSteps: true`) with `yadda@0.18.0` and upwards (`yadda@0.17.10` works ok). Eg, the following test is passing:

```javascript
// make-a-feature-steps.js

import steps from './steps';
import { expect } from 'chai';

export default function() {
  return steps()
    .then('I should find a file', function(next) {
      expect(false).ok;
      next();
    });
}
```

**Comment by adamjmcgrath** [comment]
Possibly related https://github.com/acuminous/yadda/tree/0.18.0#latest-version

**Comment by phyrog** [comment]
We're having the same problem. @adamjmcgrath did you find a workaround for this?

**Comment by adamjmcgrath** [comment]
We downgraded to yadda@0.17.10

**Comment by albertjan** [comment]
Completely missed this, I'll look into it.

**Comment by albertjan** [comment]
Better late then never. But it's fixed in master.
