### ISSUE TITLE
Using async/await

### ISSUE THREAD

**Issue by sfbwalder** [curit/ember-cli-yadda#55]
Will async/await work in ember-cli-yadda steps?  If so, can you share how it can work?

I attempted to use async/await without success as shown below.  The steps ran out of order.

```
.given('a user visits the home page', async function(next) {
      await homePage.visit();
      assert.ok(homePage.isVisible, 'at the home page');
      next();
    })
```

**Comment by ro0gr** [comment]
Seems like it's an  ember-cli-page-object related question.
Have you tried async/await with pure page objects? Does it work?

**Comment by sfbwalder** [comment]
We are using ember-cli-page-objects.  A test like this works:

```
test('search for a user at the home page', async function(assert) {
  await homePage.visit();
  assert.equal(currentURL(), '/', 'At the home page');
  await homePage.alias.fillIn('AAAA');
  await homePage.searchButton.click();
  assert.ok(homePage.searchResultsTable.isVisible, 'The search results are displayed');
});
```
Perhaps the problem is mixing the next() function with async/await.  Before I dig into the issue, I thought I would see if someone else has crossed this bridge.  Any input is welcome!

**Comment by albertjan** [comment]
I think if you return a promise from the function it should also work. you don't have to call next then. I'm pretty sure async await compiles into promises. But I'm afraid you'll have to dive into what happens when you make this function here async: https://github.com/curit/ember-cli-yadda/blob/master/lib/test-runner/qunit/component.js#L8. 😄

**Comment by albertjan** [comment]
I might just work 😁

**Comment by sfbwalder** [comment]
This is working... don't use async/await with next().
```
  .given('the user is at the search page', async function() {
    await homePage.visit();
    assert.ok(homePage.isVisible, 'at the search page');
  })
  .when('user searches by alias $alias', async function(alias) {
    homePage.alias.fillIn(alias);
    await homePage.searchButton.click();
    assert.ok(true, `searching for ${alias}`);
  })
  .then('user views the single search result', function() {
    assert.ok(homePage.searchResultsTable.isVisible, this.step);
    // more asserts
  });
```
