### ISSUE TITLE
How to add second scenario with different 'given' statement? 

### ISSUE THREAD

**Issue by olegdovger** [curit/ember-cli-yadda#7]
I have such feature:
<pre>Feature: main feature
  Scenario: 1 scenario
    When 1 step
    Then finish
  Scenario: 2 scenario
    When 2 step
    Then finish</pre>

How can I use steps from 2 different files (**steps/first.js**, **steps/second.js**) ?

<pre>import first_steps from './steps/first.js';
import first_steps from './steps/second.js';

export default function (assert) {
  return ...; // what I must return here?
}</pre>

**Comment by albertjan** [comment]
:smile: Good one never though of that.

They both import the main steps library?

**Comment by albertjan** [comment]
The idea was originally that you would create a chain of steps files so one base one for the application 

`acceptance/steps/steps.js` and then a feature specific one per feature `acceptance/steps/main-feature.js`.

But I think it's possible but you have to change the `./steps/first.js` and the `./steps/second.js` a bit.

**Comment by albertjan** [comment]
first or second steps should look something like this:

```js
export default function(steps, assert) {
  steps.given('yadda yadda', function(next) {
    assert.ok(false);
  });
});
```

```js
import steps from './steps.js`;
import first_steps from './steps/first.js';
import second_steps from './steps/first.js';

export default function (assert) {
  const first = first_steps(steps(assert), assert);
  return second_steps(first, assert);
}
```

**Comment by albertjan** [comment]
The idea is that we create __one__ library at the end. And we look for that in the `acceptance/steps` folder at the same location as your feature file with the same name.

**Comment by albertjan** [comment]
Or you could chain them: 

steps.js -> first_steps.js -> second_steps.js.

**Comment by albertjan** [comment]
@olegdovger did it work?
